learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.conf.urls import url

from . import views

urlpatterns = [
    # Home page
    url(r'^$', views.index, name='index'),

    # Show all topics.
    url(r'^topics/$', views.topics, name="topics"),

    # Detail page for a single topic
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

    # Page for adding new topic
    url(r'^new_topic/$', views.new_topic, name='new_topic'),

]

project_alpha/project_alpha/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

learning_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
	"""A topic the user is learning about. """
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	def __str__(self):
		"""Return a string representation of the model."""
		return self.text

class Entry(models.Model):
	"""Something specific learned about a topic."""
	topic = models.ForeignKey(Topic)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):

		"""Return a string representation of the model."""
		if len(self.text) > 50:
			return self.text[:50] + "..."
		else:
			return self.text

learning_logs/forms.py
from django import forms

from .models import Topic

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text': ''}

learning_logs/views.py
from django.shortcuts import render
from .models import Topic
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from .models import Topic
from .forms import TopicForm

# Create your views here.

def index(request):
	return render(request, 'learning_logs/index.html')

def topics(request):
	"""Show all topics."""
	topics = Topic.objects.order_by('date_added')
	context = {'topics': topics}
	return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
	"""Show a single topic and all its entries"""
	topic = Topic.objects.get(id=topic_id)
	entries = topic.entry_set.order_by('-date_added')
	context = {'topic': topic, 'entries': entries}
	return render(request, 'learning_logs/topic.html', context)

def new_topic(request):
	"""Add a new topic."""
	if request.method != 'POST':
		# No data submitted; create a blank form.
		form = TopicForm()
	else:
		# POST data submitted; process data.
		form = TopicForm(data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:topics'))

	context = {'form': form}
	return render(request, 'learning_logs/new_topic.html', context)

learning_logs/templates/learning_logs/base.html
<p>
	<a href="{% url 'learning_logs:index' %}">Learning Log</a> - 
	<a href="{% url 'learning_logs:topics' %}">Topics</a>
</p>

{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/index.html
<p>Learning Log</p>

<p>Learning Log helps you keep track of your learning, for any topic you're learning about.</p>

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
	<p>Add a new topic:</p>
	<form action="{% url 'learning_logs:new_topic' %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">add topic</button>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

	<p>Topic: {{ topic }}</p>

	<p>Entries:</p>

	<ul>
	{% for entry in entries %}
		<li>
		<p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
		<p>{{ entry.text|linebreaks }}</p>
		</li>
	{% empty %}
		<li>
		There are no entries for this topic yet.
		</li>
	{% endfor %}
	</ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}

	<p>Topics</p>

	<ul>
		{% for topic in topics %}
			<li>
				<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
			</li>
		{% empty %}
			<li>No topics have been added yet.</li>
		{% endfor %}
	</ul>

	<a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a>

{% endblock content %}